import AllOnesLab.Trace

/-!
# Hard direction of P12771

If `allOnes n = 1 + X + ⋯ + Xⁿ` is irreducible over `𝔽₂` (`n ≥ 2`), then
`allOnesP n = 1 + P + ⋯ + Pⁿ` with `P = X² + X + 1` is irreducible too.

The argument is Artin–Schreier: let `K = 𝔽₂[α]` with `allOnes n (α) = 0`.  Then
`Tr(α + 1) = Tr(α) + Tr(1) = 1 + n = 1` because `n` is even, so `X² + X + (α+1)`
has no root in `K` (a trace-zero obstruction), hence is irreducible over `K`.
Adjoining a root `β` gives a degree-`2n` extension of `𝔽₂` in which `P(β) = α`,
so `β` is a root of `allOnes n ∘ P = allOnesP n`; and `β` generates the whole
extension, so its minimal polynomial has degree `2n` and therefore *is*
`allOnesP n`.  Minimal polynomials are irreducible.
-/

open Polynomial

namespace AllOnesLab


/-! ## The Artin–Schreier quadratic -/

section ASBasic

variable {K : Type*} [Field K]

/-- The Artin–Schreier quadratic `X² + X + a` over a field. -/
noncomputable def asPoly (a : K) : K[X] := X ^ 2 + X + C a

lemma asPoly_monic (a : K) : (asPoly a).Monic := by
  unfold asPoly
  monicity!

lemma asPoly_natDegree (a : K) : (asPoly a).natDegree = 2 := by
  unfold asPoly
  compute_degree!

lemma asPoly_eval (a z : K) : (asPoly a).eval z = z ^ 2 + z + a := by
  simp [asPoly]

lemma aeval_asPoly {L : Type*} [CommRing L] [Algebra K L] (a : K) (z : L) :
    aeval z (asPoly a) = z ^ 2 + z + algebraMap K L a := by
  simp only [asPoly, map_add, map_pow, aeval_X, aeval_C]

end ASBasic

lemma aeval_P {L : Type*} [CommRing L] [Algebra (ZMod 2) L] (z : L) :
    aeval z P = z ^ 2 + z + 1 := by
  simp only [P, map_add, map_pow, aeval_X, map_one]

section ASTrace

variable {K : Type*} [Field K] [Algebra (ZMod 2) K] [FiniteDimensional (ZMod 2) K]

/-- Over a finite extension of `𝔽₂`, `X² + X + a` is irreducible as soon as `Tr(a) ≠ 0`:
a root would exhibit `a` as `z² + z`, which has trace `0`. -/
lemma asPoly_irreducible (a : K) (ha : Algebra.trace (ZMod 2) K a ≠ 0) :
    Irreducible (asPoly a) := by
  haveI hchar : CharP K 2 :=
    charP_of_injective_algebraMap (algebraMap (ZMod 2) K).injective 2
  refine Polynomial.irreducible_of_degree_le_three_of_not_isRoot ?_ ?_
  · simp [Finset.mem_Icc, asPoly_natDegree]
  · intro z hz
    rw [IsRoot, asPoly_eval] at hz
    have h2 : (2 : K) = 0 := by
      exact_mod_cast CharP.cast_eq_zero K 2
    have ha' : a = z ^ 2 + z := by linear_combination hz - (z ^ 2 + z) * h2
    rw [ha'] at ha
    exact ha (trace_sq_add_self_eq_zero z)

/-- **Core of the hard direction.**  Suppose `K` is a finite extension of `𝔽₂` generated by
`α`, that `Tr(α + 1) = 1`, and that `f : 𝔽₂[X]` kills `α`.  If `f.comp P` is monic of degree
`2 · [K : 𝔽₂]`, then `f.comp P` is irreducible. -/
theorem irreducible_comp_P (α : K)
    (hgenK : Algebra.adjoin (ZMod 2) ({α} : Set K) = ⊤)
    (htr : Algebra.trace (ZMod 2) K (α + 1) = 1)
    (f : (ZMod 2)[X]) (hfa : aeval α f = 0)
    (hmon : (f.comp P).Monic)
    (hdeg : (f.comp P).natDegree = 2 * Module.finrank (ZMod 2) K) :
    Irreducible (f.comp P) := by
  -- Step 2: the Artin–Schreier quadratic over `K` is irreducible.
  haveI hqfact : Fact (Irreducible (asPoly (α + 1))) :=
    ⟨asPoly_irreducible (α + 1) (by rw [htr]; exact one_ne_zero)⟩
  -- Step 3: `L := AdjoinRoot (asPoly (α+1))` is a field, `[L : K] = 2`, `[L : 𝔽₂] = 2[K:𝔽₂]`.
  haveI hfinKL : Module.Finite K (AdjoinRoot (asPoly (α + 1))) :=
    (asPoly_monic (α + 1)).finite_adjoinRoot
  haveI hfin2L : Module.Finite (ZMod 2) (AdjoinRoot (asPoly (α + 1))) :=
    Module.Finite.trans K _
  have hrankKL : Module.finrank K (AdjoinRoot (asPoly (α + 1))) = 2 := by
    have h := (AdjoinRoot.powerBasis' (asPoly_monic (α + 1))).finrank
    rw [AdjoinRoot.powerBasis'_dim, asPoly_natDegree] at h
    exact h
  have hrank2L : Module.finrank (ZMod 2) (AdjoinRoot (asPoly (α + 1)))
      = 2 * Module.finrank (ZMod 2) K := by
    rw [← Module.finrank_mul_finrank (ZMod 2) K (AdjoinRoot (asPoly (α + 1))), hrankKL, mul_comm]
  haveI hcharL : CharP (AdjoinRoot (asPoly (α + 1))) 2 :=
    charP_of_injective_algebraMap
      (algebraMap (ZMod 2) (AdjoinRoot (asPoly (α + 1)))).injective 2
  have h2L : (2 : AdjoinRoot (asPoly (α + 1))) = 0 := by
    exact_mod_cast CharP.cast_eq_zero (AdjoinRoot (asPoly (α + 1))) 2
  -- `β² + β + (α + 1) = 0` in `L`.
  have hq0 : (AdjoinRoot.root (asPoly (α + 1))) ^ 2 + AdjoinRoot.root (asPoly (α + 1))
      + algebraMap K (AdjoinRoot (asPoly (α + 1))) (α + 1) = 0 := by
    rw [← aeval_asPoly (α + 1) (AdjoinRoot.root (asPoly (α + 1))), AdjoinRoot.aeval_eq,
      AdjoinRoot.mk_self]
  -- Step 4: `P(β) = α`.
  have hPbeta : aeval (AdjoinRoot.root (asPoly (α + 1))) P
      = algebraMap K (AdjoinRoot (asPoly (α + 1))) α := by
    rw [map_add, map_one] at hq0
    rw [aeval_P]
    linear_combination hq0 - (algebraMap K (AdjoinRoot (asPoly (α + 1))) α) * h2L
  -- hence `(f ∘ P)(β) = 0`.
  have haeval : aeval (AdjoinRoot.root (asPoly (α + 1))) (f.comp P) = 0 := by
    rw [aeval_comp, hPbeta,
      ← IsScalarTower.toAlgHom_apply (ZMod 2) K (AdjoinRoot (asPoly (α + 1))) α,
      aeval_algHom_apply, hfa, map_zero]
  -- Step 5: `β` generates `L` over `𝔽₂`.
  have hKsub : ∀ x : K, algebraMap K (AdjoinRoot (asPoly (α + 1))) x ∈
      Algebra.adjoin (ZMod 2)
        ({AdjoinRoot.root (asPoly (α + 1))} : Set (AdjoinRoot (asPoly (α + 1)))) := by
    intro x
    have hmem : α ∈ Subalgebra.comap
        (IsScalarTower.toAlgHom (ZMod 2) K (AdjoinRoot (asPoly (α + 1))))
        (Algebra.adjoin (ZMod 2)
          ({AdjoinRoot.root (asPoly (α + 1))} : Set (AdjoinRoot (asPoly (α + 1))))) := by
      rw [Subalgebra.mem_comap, IsScalarTower.toAlgHom_apply, ← hPbeta]
      exact Polynomial.aeval_mem_adjoin_singleton (ZMod 2) _
    have hle := Algebra.adjoin_le (R := ZMod 2) (s := ({α} : Set K))
      (Set.singleton_subset_iff.2 hmem)
    rw [hgenK] at hle
    exact hle Algebra.mem_top
  have hgenL : Algebra.adjoin (ZMod 2)
      ({AdjoinRoot.root (asPoly (α + 1))} : Set (AdjoinRoot (asPoly (α + 1)))) = ⊤ := by
    refine Algebra.eq_top_iff.2 fun y => ?_
    -- upgrade the `𝔽₂`-subalgebra generated by `β` to a `K`-subalgebra
    let C : Subalgebra K (AdjoinRoot (asPoly (α + 1))) :=
      { (Algebra.adjoin (ZMod 2)
          ({AdjoinRoot.root (asPoly (α + 1))} :
            Set (AdjoinRoot (asPoly (α + 1))))).toSubsemiring with
        algebraMap_mem' := hKsub }
    have hβC : AdjoinRoot.root (asPoly (α + 1)) ∈ C :=
      Algebra.self_mem_adjoin_singleton (ZMod 2) _
    have hle : Algebra.adjoin K
        ({AdjoinRoot.root (asPoly (α + 1))} : Set (AdjoinRoot (asPoly (α + 1)))) ≤ C :=
      Algebra.adjoin_le (Set.singleton_subset_iff.2 hβC)
    rw [AdjoinRoot.adjoinRoot_eq_top] at hle
    exact hle Algebra.mem_top
  -- Step 6: the minimal polynomial of `β` has degree `2[K:𝔽₂]`, divides `f ∘ P`, so equals it.
  have hβint : IsIntegral (ZMod 2) (AdjoinRoot.root (asPoly (α + 1))) :=
    IsIntegral.of_finite (ZMod 2) _
  have hmintop : IntermediateField.adjoin (ZMod 2)
      ({AdjoinRoot.root (asPoly (α + 1))} : Set (AdjoinRoot (asPoly (α + 1)))) = ⊤ :=
    IntermediateField.adjoin_eq_top_of_algebra (ZMod 2) _ hgenL
  have hmindeg : (minpoly (ZMod 2) (AdjoinRoot.root (asPoly (α + 1)))).natDegree
      = 2 * Module.finrank (ZMod 2) K := by
    rw [← IntermediateField.adjoin.finrank hβint]
    have e := (IntermediateField.equivOfEq hmintop).trans
      (IntermediateField.topEquiv (F := ZMod 2) (E := AdjoinRoot (asPoly (α + 1))))
    rw [e.toLinearEquiv.finrank_eq]
    exact hrank2L
  have hdvd : minpoly (ZMod 2) (AdjoinRoot.root (asPoly (α + 1))) ∣ f.comp P :=
    minpoly.dvd (ZMod 2) _ haeval
  have heq : f.comp P = minpoly (ZMod 2) (AdjoinRoot.root (asPoly (α + 1))) :=
    Polynomial.eq_of_monic_of_dvd_of_natDegree_le (minpoly.monic hβint) hmon hdvd
      (by rw [hdeg, hmindeg])
  rw [heq]
  exact minpoly.irreducible hβint

end ASTrace

/-! ## The theorem -/

/-- Hard direction of P12771 (Artin–Schreier / trace argument). -/
theorem irreducible_allOnesP_of_irreducible_allOnes (n : ℕ) (hn : 2 ≤ n)
    (h : Irreducible (allOnes n)) : Irreducible (allOnesP n) := by
  haveI hfact : Fact (Irreducible (allOnes n)) := ⟨h⟩
  haveI hfin : Module.Finite (ZMod 2) (AdjoinRoot (allOnes n)) :=
    (allOnes_monic n).finite_adjoinRoot
  have hrank : Module.finrank (ZMod 2) (AdjoinRoot (allOnes n)) = n := by
    have h' := (AdjoinRoot.powerBasis' (allOnes_monic n)).finrank
    rw [AdjoinRoot.powerBasis'_dim, allOnes_natDegree] at h'
    exact h'
  -- Step 1: `Tr(α + 1) = Tr(α) + Tr(1) = 1 + n = 1`, since `n` is even.
  have hev : ((n : ℕ) : ZMod 2) = 0 :=
    (CharP.cast_eq_zero_iff (ZMod 2) 2 n).2 (even_of_irreducible_allOnes n hn h).two_dvd
  have htr : Algebra.trace (ZMod 2) (AdjoinRoot (allOnes n))
      (AdjoinRoot.root (allOnes n) + 1) = 1 := by
    rw [map_add, trace_root_allOnes n (by omega), trace_one_allOnes n, hev, add_zero]
  rw [allOnesP_eq_comp]
  refine irreducible_comp_P (AdjoinRoot.root (allOnes n)) AdjoinRoot.adjoinRoot_eq_top htr
    (allOnes n) ?_ ?_ ?_
  · rw [AdjoinRoot.aeval_eq, AdjoinRoot.mk_self]
  · rw [← allOnesP_eq_comp]; exact allOnesP_monic n
  · rw [← allOnesP_eq_comp, allOnesP_natDegree, hrank]

#print axioms AllOnesLab.irreducible_allOnesP_of_irreducible_allOnes

end AllOnesLab
